import { useMutation, useQuery } from '@tanstack/react-query';
import { useParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import { api } from '@/lib/api';
import type { Competition } from '@/types/api';
import { PageHeader } from '@/components/PageHeader';
import { QuizRunner, type SubmitResult } from '@/components/QuizRunner';
import { Card, ErrorState, PageSkeleton, StatusPill } from '@/components/ui';
import { faNumber, remaining } from '@/lib/utils';
export function CompetitionDetailPage(){const{id}=useParams();const q=useQuery({queryKey:['competition',id],queryFn:async()=>(await api.get<Competition>(`/competitions/${id}`)).data,enabled:Boolean(id)});const submit=useMutation({mutationFn:async(payload:{answers:{questionId:string;option:number}[];durationMs:number})=>(await api.post<SubmitResult>(`/competitions/${id}/submit`,payload)).data,onError:e=>toast.error((e as Error).message)});if(q.isLoading)return <PageSkeleton/>;if(q.error||!q.data)return <div className="p-4"><ErrorState message={(q.error as Error)?.message||'مسابقه پیدا نشد'}/></div>;const c=q.data;const available=c.status==='active'&&(c.attempts?.length??0)<c.attemptLimit;return <><PageHeader title={c.title} subtitle={c.prize||'مسابقه فوتبالی'} back/><main className="space-y-4 p-4"><Card className="overflow-hidden p-0">{c.coverImage&&<img src={c.coverImage} alt="" className="h-44 w-full object-cover"/>}<div className="p-4"><div className="flex items-center justify-between"><StatusPill status={c.status}/><span className="text-xs text-pitch-300">{remaining(c.endsAt)}</span></div><p className="mt-4 text-sm leading-7 text-slate-300">{c.description}</p><div className="mt-4 grid grid-cols-2 gap-2"><div className="surface-soft p-3 text-xs"><span className="text-slate-400">تلاش مجاز</span><strong className="mt-1 block">{faNumber(c.attemptLimit)}</strong></div><div className="surface-soft p-3 text-xs"><span className="text-slate-400">تلاش انجام‌شده</span><strong className="mt-1 block">{faNumber(c.attempts?.length??0)}</strong></div></div></div></Card>{available&&c.questionIds?.length?<QuizRunner questions={c.questionIds} submitting={submit.isPending} onSubmit={async(answers,durationMs)=>submit.mutateAsync({answers,durationMs})}/>:<Card className="text-center text-sm text-slate-400">{c.status!=='active'?'این مسابقه در حال حاضر فعال نیست.':'تعداد تلاش مجاز شما تمام شده است.'}</Card>}</main></>}
