import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, AlertTriangle, Calculator, Check, Edit3, LoaderCircle, Plus, RefreshCw, Save, Search, ShieldCheck, ToggleLeft, Users, X } from 'lucide-react';
import toast from 'react-hot-toast';
import { Navigate } from 'react-router-dom';
import { PageHeader } from '@/components/PageHeader';
import { Card, EmptyState, ErrorState, LoadingButton, PageSkeleton } from '@/components/ui';
import { useBootstrap } from '@/hooks/useBootstrap';
import { api } from '@/lib/api';
import { cn, faNumber, tehranDate } from '@/lib/utils';

type Tab = 'teams'|'players'|'scoring'|'stats';
type Position = 'GK'|'DEF'|'MID'|'FWD';
interface Team { _id:string; externalApiId?:number; name:string; shortName:string; logoUrl?:string; country:string; league:string; active:boolean }
interface Player { _id:string; externalApiId?:number; name:string; photoUrl?:string; position:Position; realTeamId:Team; nationality:string; active:boolean; lastSyncedAt?:string; syncError?:string }
interface MatchOption { _id:string; externalApiId?:number; homeTeam:string; awayTeam:string; competitionName:string; kickoffAt:string }
interface Options { teams:Team[]; matches:MatchOption[] }
interface PageData<T> { items:T[]; total:number; page:number; pages:number }
interface SyncRun { status:'running'|'completed'|'failed'; processed:number; errorMessages:string[]; startedAt:string; completedAt?:string }
interface SyncStatus { players:SyncRun|null; statistics:SyncRun|null }
interface Rules { minutesPlayed:number; goalGoalkeeper:number; goalDefender:number; goalMidfielder:number; goalForward:number; assist:number; cleanSheet:number; save:number; yellowCard:number; redCard:number; ownGoal:number; missedPenalty:number }
interface ScoringConfig { version:number; rules:Rules; history:Array<{version:number;reason:string;changedAt:string;rules:Rules}> }
interface StatValues { minutes:number; goals:number; assists:number; yellowCards:number; redCards:number; saves:number; cleanSheet:boolean; ownGoals:number; missedPenalties:number }
interface PlayerStat extends StatValues { _id:string; playerId:Player; matchId:MatchOption; fantasyPoints:number; scoringVersion:number; source:'external'|'manual'|'corrected'; lastSyncedAt?:string; corrections:unknown[] }

const tabs:Array<{key:Tab;label:string;icon:typeof Users}>=[
  {key:'teams',label:'تیم‌ها',icon:ShieldCheck},
  {key:'players',label:'بازیکنان',icon:Users},
  {key:'scoring',label:'امتیازدهی',icon:Calculator},
  {key:'stats',label:'آمار بازی',icon:Activity}
];

export function FantasyAdminPage() {
  const bootstrap = useBootstrap();
  const [tab,setTab]=useState<Tab>('teams');
  const options=useQuery({queryKey:['adminFantasyOptions'],queryFn:async()=>(await api.get<Options>('/admin/fantasy/options')).data,enabled:Boolean(bootstrap.data?.isAdmin)});
  if(bootstrap.isLoading)return <PageSkeleton/>;
  if(!bootstrap.data?.isAdmin)return <Navigate to="/" replace/>;
  return <><PageHeader title="مدیریت فانتزی" subtitle="تیم، بازیکن، قوانین و آمار مسابقه" back backTo="/admin" admin/><main className="space-y-4 p-4"><div className="grid grid-cols-4 gap-1 rounded-2xl border border-white/[.07] bg-white/[.025] p-1">{tabs.map(({key,label,icon:Icon})=><button key={key} onClick={()=>setTab(key)} className={cn('flex min-h-12 flex-col items-center justify-center gap-1 rounded-xl text-[8px] font-bold text-slate-500',tab===key&&'bg-sky-300/[.12] text-sky-200')}><Icon size={16}/>{label}</button>)}</div>{options.isLoading?<PageSkeleton/>:options.error?<ErrorState message={(options.error as Error).message} onRetry={()=>options.refetch()}/>:tab==='teams'?<TeamsPanel/>:tab==='players'?<PlayersPanel teams={options.data?.teams??[]}/>:tab==='scoring'?<ScoringPanel/>:<StatsPanel options={options.data!}/>}</main></>;
}

function TeamsPanel(){
  const qc=useQueryClient();const[q,setQ]=useState('');const[active,setActive]=useState('all');const[league,setLeague]=useState('');const[country,setCountry]=useState('');const[page,setPage]=useState(1);const[editor,setEditor]=useState<Team|null|undefined>();
  const query=useQuery({queryKey:['fantasyTeams',q,active,league,country,page],queryFn:async()=>(await api.get<PageData<Team>>('/admin/fantasy/teams',{params:{q:q||undefined,active,league:league||undefined,country:country||undefined,page,limit:15}})).data});
  const toggle=useMutation({mutationFn:async(team:Team)=>api.patch(`/admin/fantasy/teams/${team._id}`,{active:!team.active}),onSuccess:async()=>{toast.success('وضعیت تیم تغییر کرد');await invalidateFantasy(qc,'fantasyTeams')},onError:error=>toast.error((error as Error).message)});
  const remove=useMutation({mutationFn:async(team:Team)=>api.delete(`/admin/fantasy/teams/${team._id}`),onSuccess:async()=>{toast.success('تیم حذف شد');await invalidateFantasy(qc,'fantasyTeams')},onError:error=>toast.error((error as Error).message)});
  return <section className="space-y-3"><SectionHead title="تیم‌های واقعی" subtitle="تیم‌های مرجع مسابقات و بازیکنان" onAdd={()=>setEditor(null)}/><FilterRow q={q} setQ={value=>{setQ(value);setPage(1)}} active={active} setActive={value=>{setActive(value);setPage(1)}}/><div className="grid grid-cols-2 gap-2"><input className="input" value={league} onChange={event=>{setLeague(event.target.value);setPage(1)}} placeholder="فیلتر لیگ"/><input className="input" value={country} onChange={event=>{setCountry(event.target.value);setPage(1)}} placeholder="فیلتر کشور"/></div>{query.isLoading?<PageSkeleton/>:query.error?<ErrorState message={(query.error as Error).message} onRetry={()=>query.refetch()}/>:query.data?.items.length?<>{query.data.items.map(team=><Card key={team._id} className="p-3"><div className="flex items-center gap-3">{team.logoUrl?<img src={team.logoUrl} alt="" className="h-11 w-11 rounded-xl object-contain"/>:<span className="grid h-11 w-11 place-items-center rounded-xl bg-sky-300/[.08] text-xs font-black text-sky-300">{team.shortName.slice(0,2)}</span>}<div className="min-w-0 flex-1"><h3 className="truncate text-xs font-black">{team.name}</h3><p className="mt-1 truncate text-[9px] text-slate-500">{team.league} · {team.country}{team.externalApiId?` · API ${team.externalApiId}`:''}</p></div><StateDot active={team.active}/></div><div className="mt-3 grid grid-cols-3 gap-2"><button className="btn-secondary px-2 text-[9px]" onClick={()=>setEditor(team)}><Edit3 size={14}/>ویرایش</button><button className="btn-secondary px-2 text-[9px]" onClick={()=>toggle.mutate(team)}><ToggleLeft size={15}/>{team.active?'غیرفعال':'فعال'}</button><button className="btn-secondary px-2 text-[9px] text-rose-300" onClick={()=>{if(confirm('این تیم حذف شود؟'))remove.mutate(team)}}>حذف</button></div></Card>)}<Pager page={page} pages={query.data.pages} onPage={setPage}/></>:<EmptyState title="تیمی پیدا نشد" description="فیلترها را تغییر دهید یا تیم تازه‌ای بسازید."/>}{editor!==undefined&&<TeamEditor item={editor} onClose={()=>setEditor(undefined)} onSaved={async()=>{setEditor(undefined);await Promise.all([invalidateFantasy(qc,'fantasyTeams'),qc.invalidateQueries({queryKey:['adminFantasyOptions']})])}}/>}</section>;
}

function PlayersPanel({teams}:{teams:Team[]}){
  const qc=useQueryClient();const[q,setQ]=useState('');const[active,setActive]=useState('all');const[teamId,setTeamId]=useState('');const[position,setPosition]=useState('');const[page,setPage]=useState(1);const[editor,setEditor]=useState<Player|null|undefined>();
  const query=useQuery({queryKey:['fantasyPlayers',q,active,teamId,position,page],queryFn:async()=>(await api.get<PageData<Player>>('/admin/fantasy/players',{params:{q:q||undefined,active,teamId:teamId||undefined,position:position||undefined,page,limit:15}})).data});
  const status=useQuery({queryKey:['fantasySyncStatus'],queryFn:async()=>(await api.get<SyncStatus>('/admin/fantasy/sync-status')).data});
  const sync=useMutation({mutationFn:async()=>api.post('/admin/fantasy/players/sync',{}),onSuccess:async()=>{toast.success('همگام‌سازی بازیکنان تمام شد');await Promise.all([invalidateFantasy(qc,'fantasyPlayers'),qc.invalidateQueries({queryKey:['fantasySyncStatus']}),qc.invalidateQueries({queryKey:['adminFantasyOptions']})])},onError:error=>toast.error((error as Error).message)});
  const toggle=useMutation({mutationFn:async(player:Player)=>api.patch(`/admin/fantasy/players/${player._id}`,{active:!player.active}),onSuccess:async()=>{toast.success('وضعیت بازیکن تغییر کرد');await invalidateFantasy(qc,'fantasyPlayers')},onError:error=>toast.error((error as Error).message)});
  return <section className="space-y-3"><SectionHead title="بازیکنان واقعی" subtitle="بدون OVR یا امتیاز ساختگی" onAdd={()=>setEditor(null)} extra={<LoadingButton loading={sync.isPending} onClick={()=>sync.mutate()} className="min-h-10 px-3 text-[9px]"><RefreshCw size={14}/>همگام‌سازی</LoadingButton>}/><SyncSummary run={status.data?.players}/><FilterRow q={q} setQ={value=>{setQ(value);setPage(1)}} active={active} setActive={value=>{setActive(value);setPage(1)}}/><div className="grid grid-cols-2 gap-2"><select className="input" value={teamId} onChange={event=>{setTeamId(event.target.value);setPage(1)}}><option value="">همه تیم‌ها</option>{teams.map(team=><option key={team._id} value={team._id}>{team.name}</option>)}</select><select className="input" value={position} onChange={event=>{setPosition(event.target.value);setPage(1)}}><option value="">همه پست‌ها</option>{positionOptions.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></div>{query.isLoading?<PageSkeleton/>:query.error?<ErrorState message={(query.error as Error).message} onRetry={()=>query.refetch()}/>:query.data?.items.length?<>{query.data.items.map(player=><Card key={player._id} className="p-3"><div className="flex items-center gap-3">{player.photoUrl?<img src={player.photoUrl} alt="" className="h-12 w-12 rounded-xl object-cover"/>:<span className="grid h-12 w-12 place-items-center rounded-xl bg-emerald-300/[.08] font-black text-emerald-300">{player.name.slice(0,1)}</span>}<div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="truncate text-xs font-black">{player.name}</h3><span className="rounded-lg bg-white/[.06] px-1.5 py-1 text-[8px]">{positionLabel(player.position)}</span></div><p className="mt-1 truncate text-[9px] text-slate-500">{player.realTeamId?.name} · {player.nationality}</p><p className="mt-1 text-[8px] text-slate-600">{player.lastSyncedAt?`آخرین همگام‌سازی: ${tehranDate(player.lastSyncedAt)}`:'ثبت دستی'}</p></div><StateDot active={player.active}/></div>{player.syncError&&<p className="mt-2 rounded-xl bg-rose-400/[.08] p-2 text-[8px] leading-4 text-rose-300">{player.syncError}</p>}<div className="mt-3 grid grid-cols-2 gap-2"><button className="btn-secondary px-2 text-[9px]" onClick={()=>setEditor(player)}><Edit3 size={14}/>ویرایش</button><button className="btn-secondary px-2 text-[9px]" onClick={()=>toggle.mutate(player)}><ToggleLeft size={15}/>{player.active?'غیرفعال':'فعال'}</button></div></Card>)}<Pager page={page} pages={query.data.pages} onPage={setPage}/></>:<EmptyState title="بازیکنی پیدا نشد" description="از API همگام‌سازی کنید یا بازیکن را دستی بسازید."/>}{editor!==undefined&&<PlayerEditor item={editor} teams={teams} onClose={()=>setEditor(undefined)} onSaved={async()=>{setEditor(undefined);await invalidateFantasy(qc,'fantasyPlayers')}}/>}</section>;
}

function ScoringPanel(){
  const query=useQuery({queryKey:['fantasyScoring'],queryFn:async()=>(await api.get<ScoringConfig>('/admin/fantasy/scoring')).data});
  if(query.isLoading||!query.data)return <PageSkeleton/>;if(query.error)return <ErrorState message={(query.error as Error).message} onRetry={()=>query.refetch()}/>;
  return <ScoringEditor key={query.data.version} config={query.data}/>;
}
function ScoringEditor({config}:{config:ScoringConfig}){
  const qc=useQueryClient();const[rules,setRules]=useState<Rules>(config.rules);const[reason,setReason]=useState('');
  const save=useMutation({mutationFn:async()=>api.put('/admin/fantasy/scoring',{rules,reason}),onSuccess:async(response)=>{toast.success(`${faNumber(response.data.recalculated)} رکورد دوباره محاسبه شد`);setReason('');await qc.invalidateQueries({queryKey:['fantasyScoring']})},onError:error=>toast.error((error as Error).message)});
  return <section className="space-y-4"><div><h2 className="text-sm font-black">قوانین امتیازدهی فانتزی</h2><p className="mt-1 text-[9px] text-slate-500">نسخه {faNumber(config.version)} · تغییر قوانین همه آمارها را دوباره محاسبه می‌کند.</p></div><Card className="grid grid-cols-2 gap-3 p-3">{ruleFields.map(field=><label key={field.key}><span className="label text-[9px]">{field.label}</span><input className="input" type="number" step="0.01" value={rules[field.key]} onChange={event=>setRules({...rules,[field.key]:Number(event.target.value)})}/></label>)}</Card><label><span className="label">دلیل تغییر</span><textarea className="input min-h-20" value={reason} onChange={event=>setReason(event.target.value)} placeholder="دلیل تغییر قوانین را ثبت کنید" maxLength={500}/></label><LoadingButton loading={save.isPending} disabled={reason.trim().length<5} onClick={()=>save.mutate()} className="w-full"><Save size={17}/>ذخیره و محاسبه مجدد</LoadingButton><div><h3 className="mb-2 text-xs font-black">تاریخچه تغییرات</h3><div className="space-y-2">{config.history.slice().reverse().map(item=><Card key={`${item.version}-${item.changedAt}`} className="p-3"><div className="flex justify-between gap-3"><strong className="text-[10px]">نسخه {faNumber(item.version)}</strong><span className="text-[8px] text-slate-500">{tehranDate(item.changedAt)}</span></div><p className="mt-2 text-[9px] leading-5 text-slate-400">{item.reason}</p><details className="mt-2"><summary className="cursor-pointer text-[8px] text-sky-300">مشاهده مقادیر این نسخه</summary><div className="mt-2 grid grid-cols-2 gap-1">{ruleFields.map(field=><span key={field.key} className="rounded-lg bg-white/[.035] p-1.5 text-[7px] text-slate-500">{field.label}: <b className="text-slate-300">{faNumber(item.rules[field.key])}</b></span>)}</div></details></Card>)}{!config.history.length&&<p className="py-4 text-center text-[9px] text-slate-500">هنوز تغییری ثبت نشده است.</p>}</div></div></section>;
}

function StatsPanel({options}:{options:Options}){
  const qc=useQueryClient();const[matchId,setMatchId]=useState('');const[playerId,setPlayerId]=useState('');const[playerQ,setPlayerQ]=useState('');const[page,setPage]=useState(1);const[correcting,setCorrecting]=useState<PlayerStat|null>(null);
  const players=useQuery({queryKey:['fantasyPlayerOptions'],queryFn:async()=>(await api.get<PageData<Player>>('/admin/fantasy/players',{params:{limit:100,active:'all'}})).data});
  const query=useQuery({queryKey:['fantasyStats',matchId,playerId,playerQ,page],queryFn:async()=>(await api.get<PageData<PlayerStat>>('/admin/fantasy/stats',{params:{matchId:matchId||undefined,playerId:playerId||undefined,q:playerQ||undefined,page,limit:15}})).data});
  const status=useQuery({queryKey:['fantasySyncStatus'],queryFn:async()=>(await api.get<SyncStatus>('/admin/fantasy/sync-status')).data});
  const sync=useMutation({mutationFn:async()=>api.post('/admin/fantasy/stats/sync',{matchId}),onSuccess:async()=>{toast.success('آمار مسابقه همگام‌سازی شد');await Promise.all([invalidateFantasy(qc,'fantasyStats'),qc.invalidateQueries({queryKey:['fantasySyncStatus']}),qc.invalidateQueries({queryKey:['fantasyScoring']})])},onError:error=>toast.error((error as Error).message)});
  return <section className="space-y-3"><div><h2 className="text-sm font-black">آمار بازیکن در مسابقه</h2><p className="mt-1 text-[9px] text-slate-500">آمار واردشده و امتیاز محاسبه‌شده با قوانین فعال</p></div><SyncSummary run={status.data?.statistics}/><div className="grid gap-2"><select className="input" value={matchId} onChange={event=>{setMatchId(event.target.value);setPage(1)}}><option value="">همه مسابقات</option>{options.matches.map(match=><option key={match._id} value={match._id}>{match.homeTeam} — {match.awayTeam} · {tehranDate(match.kickoffAt)}</option>)}</select><select className="input" value={playerId} onChange={event=>{setPlayerId(event.target.value);setPage(1)}}><option value="">همه بازیکنان</option>{players.data?.items.map(player=><option key={player._id} value={player._id}>{player.name} · {player.realTeamId?.name}</option>)}</select><input className="input" value={playerQ} onChange={event=>{setPlayerQ(event.target.value);setPlayerId('');setPage(1)}} placeholder="جست‌وجوی نام بازیکن در همه آمارها"/><LoadingButton loading={sync.isPending} disabled={!matchId} onClick={()=>sync.mutate()} className="w-full"><RefreshCw size={15}/>دریافت آمار مسابقه انتخاب‌شده</LoadingButton></div>{query.isLoading?<PageSkeleton/>:query.error?<ErrorState message={(query.error as Error).message} onRetry={()=>query.refetch()}/>:query.data?.items.length?<>{query.data.items.map(stat=><Card key={stat._id} className="p-3"><div className="flex items-center gap-3"><div className="min-w-0 flex-1"><h3 className="truncate text-xs font-black">{stat.playerId?.name}</h3><p className="mt-1 truncate text-[9px] text-slate-500">{stat.matchId?.homeTeam} — {stat.matchId?.awayTeam}</p></div><div className="text-left"><strong className="text-lg font-black text-amber-300">{faNumber(stat.fantasyPoints)}</strong><p className="text-[7px] text-slate-600">امتیاز فانتزی</p></div></div><div className="mt-3 grid grid-cols-4 gap-1 text-center">{[['دقیقه',stat.minutes],['گل',stat.goals],['پاس گل',stat.assists],['سیو',stat.saves],['زرد',stat.yellowCards],['قرمز',stat.redCards],['کلین‌شیت',stat.cleanSheet?'بله':'خیر'],['اصلاح',stat.corrections?.length??0]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-white/[.035] p-2"><strong className="block text-[10px]">{typeof value==='number'?faNumber(value):value}</strong><span className="text-[7px] text-slate-600">{label}</span></div>)}</div><button className="btn-secondary mt-3 w-full text-[9px]" onClick={()=>setCorrecting(stat)}><Edit3 size={14}/>اصلاح دستی امن</button></Card>)}<Pager page={page} pages={query.data.pages} onPage={setPage}/></>:<EmptyState title="آماری پیدا نشد" description="یک مسابقه دارای شناسه API را همگام‌سازی کنید."/>}{correcting&&<CorrectionEditor stat={correcting} onClose={()=>setCorrecting(null)} onSaved={async()=>{setCorrecting(null);await invalidateFantasy(qc,'fantasyStats')}}/>}</section>;
}

function TeamEditor({item,onClose,onSaved}:{item:Team|null;onClose:()=>void;onSaved:()=>void}){const[form,setForm]=useState({externalApiId:item?.externalApiId?.toString()??'',name:item?.name??'',shortName:item?.shortName??'',logoUrl:item?.logoUrl??'',country:item?.country??'',league:item?.league??'',active:item?.active??true});const save=useMutation({mutationFn:async()=>{const payload={...form,externalApiId:form.externalApiId?Number(form.externalApiId):undefined,logoUrl:form.logoUrl||undefined};return item?api.patch(`/admin/fantasy/teams/${item._id}`,payload):api.post('/admin/fantasy/teams',payload)},onSuccess:()=>{toast.success(item?'تیم ذخیره شد':'تیم ایجاد شد');void onSaved()},onError:error=>toast.error((error as Error).message)});return <Sheet title={item?'ویرایش تیم':'تیم جدید'} onClose={onClose}><TextInput label="شناسه API" type="number" value={form.externalApiId} onChange={value=>setForm({...form,externalApiId:value})}/><TextInput label="نام تیم" value={form.name} onChange={value=>setForm({...form,name:value})}/><TextInput label="نام کوتاه" value={form.shortName} onChange={value=>setForm({...form,shortName:value})}/><TextInput label="لوگو URL" value={form.logoUrl} onChange={value=>setForm({...form,logoUrl:value})}/><TextInput label="کشور" value={form.country} onChange={value=>setForm({...form,country:value})}/><TextInput label="لیگ" value={form.league} onChange={value=>setForm({...form,league:value})}/><CheckInput label="فعال باشد" checked={form.active} onChange={active=>setForm({...form,active})}/><LoadingButton loading={save.isPending} disabled={!form.name.trim()||!form.shortName.trim()||!form.country.trim()||!form.league.trim()} onClick={()=>save.mutate()} className="w-full"><Save size={16}/>ذخیره</LoadingButton></Sheet>}
function PlayerEditor({item,teams,onClose,onSaved}:{item:Player|null;teams:Team[];onClose:()=>void;onSaved:()=>void}){const[form,setForm]=useState({externalApiId:item?.externalApiId?.toString()??'',name:item?.name??'',photoUrl:item?.photoUrl??'',position:item?.position??'MID' as Position,realTeamId:item?.realTeamId?._id??'',nationality:item?.nationality??'',active:item?.active??true});const save=useMutation({mutationFn:async()=>{const payload={...form,externalApiId:form.externalApiId?Number(form.externalApiId):undefined,photoUrl:form.photoUrl||undefined};return item?api.patch(`/admin/fantasy/players/${item._id}`,payload):api.post('/admin/fantasy/players',payload)},onSuccess:()=>{toast.success(item?'بازیکن ذخیره شد':'بازیکن ایجاد شد');void onSaved()},onError:error=>toast.error((error as Error).message)});return <Sheet title={item?'ویرایش بازیکن':'بازیکن جدید'} onClose={onClose}><TextInput label="شناسه API" type="number" value={form.externalApiId} onChange={value=>setForm({...form,externalApiId:value})}/><TextInput label="نام بازیکن" value={form.name} onChange={value=>setForm({...form,name:value})}/><TextInput label="عکس URL" value={form.photoUrl} onChange={value=>setForm({...form,photoUrl:value})}/><label><span className="label">پست</span><select className="input" value={form.position} onChange={event=>setForm({...form,position:event.target.value as Position})}>{positionOptions.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label><span className="label">تیم واقعی</span><select className="input" value={form.realTeamId} onChange={event=>setForm({...form,realTeamId:event.target.value})}><option value="">انتخاب تیم</option>{teams.map(team=><option key={team._id} value={team._id}>{team.name}</option>)}</select></label><TextInput label="ملیت" value={form.nationality} onChange={value=>setForm({...form,nationality:value})}/><CheckInput label="فعال باشد" checked={form.active} onChange={active=>setForm({...form,active})}/><LoadingButton loading={save.isPending} disabled={!form.name.trim()||!form.realTeamId||!form.nationality.trim()} onClick={()=>save.mutate()} className="w-full"><Save size={16}/>ذخیره</LoadingButton></Sheet>}
function CorrectionEditor({stat,onClose,onSaved}:{stat:PlayerStat;onClose:()=>void;onSaved:()=>void}){const[values,setValues]=useState<StatValues>({minutes:stat.minutes,goals:stat.goals,assists:stat.assists,yellowCards:stat.yellowCards,redCards:stat.redCards,saves:stat.saves,cleanSheet:stat.cleanSheet,ownGoals:stat.ownGoals,missedPenalties:stat.missedPenalties});const[reason,setReason]=useState('');const save=useMutation({mutationFn:async()=>api.patch(`/admin/fantasy/stats/${stat._id}/correct`,{values,reason}),onSuccess:()=>{toast.success('اصلاح ثبت و امتیاز دوباره محاسبه شد');void onSaved()},onError:error=>toast.error((error as Error).message)});return <Sheet title={`اصلاح آمار ${stat.playerId?.name}`} onClose={onClose}><div className="grid grid-cols-2 gap-3">{statNumberFields.map(field=><label key={field.key}><span className="label text-[9px]">{field.label}</span><input className="input" type="number" min="0" value={values[field.key]} onChange={event=>setValues({...values,[field.key]:Number(event.target.value)})}/></label>)}</div><CheckInput label="کلین‌شیت" checked={values.cleanSheet} onChange={cleanSheet=>setValues({...values,cleanSheet})}/><label><span className="label">دلیل اجباری اصلاح</span><textarea className="input min-h-20" value={reason} onChange={event=>setReason(event.target.value)} maxLength={500}/></label><LoadingButton loading={save.isPending} disabled={reason.trim().length<5} onClick={()=>save.mutate()} className="w-full"><Check size={16}/>ثبت اصلاح و محاسبه</LoadingButton></Sheet>}

function SectionHead({title,subtitle,onAdd,extra}:{title:string;subtitle:string;onAdd:()=>void;extra?:React.ReactNode}){return <div className="flex items-end justify-between gap-2"><div><h2 className="text-sm font-black">{title}</h2><p className="mt-1 text-[9px] text-slate-500">{subtitle}</p></div><div className="flex gap-2">{extra}<button className="btn-primary min-h-10 px-3 text-[9px]" onClick={onAdd}><Plus size={15}/>افزودن</button></div></div>}
function FilterRow({q,setQ,active,setActive}:{q:string;setQ:(v:string)=>void;active:string;setActive:(v:string)=>void}){return <div className="grid grid-cols-[1fr_110px] gap-2"><label className="relative"><Search size={15} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-600"/><input className="input pr-9" value={q} onChange={event=>setQ(event.target.value)} placeholder="جست‌وجو..."/></label><select className="input" value={active} onChange={event=>setActive(event.target.value)}><option value="all">همه</option><option value="true">فعال</option><option value="false">غیرفعال</option></select></div>}
function Pager({page,pages,onPage}:{page:number;pages:number;onPage:(v:number)=>void}){if(pages<=1)return null;return <div className="flex items-center justify-between"><button className="btn-secondary min-h-10 px-4 text-[9px]" disabled={page<=1} onClick={()=>onPage(page-1)}>قبلی</button><span className="text-[9px] text-slate-500">صفحه {faNumber(page)} از {faNumber(pages)}</span><button className="btn-secondary min-h-10 px-4 text-[9px]" disabled={page>=pages} onClick={()=>onPage(page+1)}>بعدی</button></div>}
function Sheet({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[90] flex items-end bg-black/75" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><div className="safe-bottom max-h-[92vh] w-full overflow-y-auto rounded-t-[30px] border-t border-white/10 bg-ink-900 p-4"><div className="mx-auto max-w-xl space-y-4"><div className="flex items-center justify-between"><h2 className="font-black">{title}</h2><button className="grid h-10 w-10 place-items-center rounded-xl bg-white/[.06]" onClick={onClose}><X size={18}/></button></div>{children}</div></div></div>}
function TextInput({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label><span className="label">{label}</span><input className="input" type={type} value={value} onChange={event=>onChange(event.target.value)}/></label>}
function CheckInput({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex min-h-12 items-center justify-between rounded-2xl border border-white/[.08] bg-white/[.035] px-4 text-xs font-bold"><span>{label}</span><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)} className="h-5 w-5 accent-emerald-500"/></label>}
function StateDot({active}:{active:boolean}){return <span title={active?'فعال':'غیرفعال'} className={cn('h-2.5 w-2.5 shrink-0 rounded-full',active?'bg-emerald-400':'bg-slate-600')}/>}
function SyncSummary({run}:{run?:SyncRun|null}){if(!run)return <Card className="p-3 text-[9px] text-slate-500">هنوز همگام‌سازی انجام نشده است.</Card>;return <Card className={cn('p-3',run.status==='failed'&&'border-rose-400/20')}><div className="flex items-center gap-2">{run.status==='running'?<LoaderCircle size={15} className="animate-spin text-sky-300"/>:run.status==='failed'?<AlertTriangle size={15} className="text-rose-300"/>:<Check size={15} className="text-emerald-300"/>}<p className="text-[9px]">آخرین همگام‌سازی: {tehranDate(run.completedAt??run.startedAt)} · {faNumber(run.processed)} رکورد</p></div>{run.errorMessages?.length>0&&<details className="mt-2"><summary className="cursor-pointer text-[8px] text-rose-300">{faNumber(run.errorMessages.length)} خطا یا هشدار</summary><div className="mt-2 max-h-28 overflow-y-auto rounded-xl bg-rose-400/[.06] p-2 text-[8px] leading-5 text-rose-200">{run.errorMessages.map((error,index)=><p key={`${error}-${index}`}>{error}</p>)}</div></details>}</Card>}
async function invalidateFantasy(qc:ReturnType<typeof useQueryClient>,key:string){await qc.invalidateQueries({queryKey:[key]})}
const positionOptions:Array<{value:Position;label:string}>=[{value:'GK',label:'دروازه‌بان'},{value:'DEF',label:'مدافع'},{value:'MID',label:'هافبک'},{value:'FWD',label:'مهاجم'}];
function positionLabel(position:Position){return positionOptions.find(item=>item.value===position)?.label??position}
const ruleFields:Array<{key:keyof Rules;label:string}>=[{key:'minutesPlayed',label:'هر دقیقه بازی'},{key:'goalGoalkeeper',label:'گل دروازه‌بان'},{key:'goalDefender',label:'گل مدافع'},{key:'goalMidfielder',label:'گل هافبک'},{key:'goalForward',label:'گل مهاجم'},{key:'assist',label:'پاس گل'},{key:'cleanSheet',label:'کلین‌شیت'},{key:'save',label:'هر مهار'},{key:'yellowCard',label:'کارت زرد'},{key:'redCard',label:'کارت قرمز'},{key:'ownGoal',label:'گل‌به‌خودی'},{key:'missedPenalty',label:'پنالتی ازدست‌رفته'}];
const statNumberFields:Array<{key:Exclude<keyof StatValues,'cleanSheet'>;label:string}>=[{key:'minutes',label:'دقایق'},{key:'goals',label:'گل'},{key:'assists',label:'پاس گل'},{key:'saves',label:'مهار'},{key:'yellowCards',label:'کارت زرد'},{key:'redCards',label:'کارت قرمز'},{key:'ownGoals',label:'گل‌به‌خودی'},{key:'missedPenalties',label:'پنالتی ازدست‌رفته'}];
