import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Crown, Medal, Target, UserPlus } from 'lucide-react';
import { api } from '@/lib/api';
import { cn, faNumber } from '@/lib/utils';
import type { User } from '@/types/api';
import { PageHeader } from '@/components/PageHeader';
import { Card, ErrorState, PageSkeleton } from '@/components/ui';
const tabs=[{v:'weekly',l:'هفتگی',icon:Medal},{v:'all',l:'همیشگی',icon:Crown},{v:'predictors',l:'پیش‌بینی',icon:Target},{v:'referrals',l:'دعوت',icon:UserPlus}];
interface RankingData{type:string;leaders:User[];current:User&{rank:number}}
export function RankingsPage(){const[type,setType]=useState('weekly');const q=useQuery({queryKey:['rankings',type],queryFn:async()=>(await api.get<RankingData>('/rankings',{params:{type}})).data});return <><PageHeader title="رتبه‌بندی" subtitle="جایگاهت را بین فوتبالی‌ها ببین"/><main className="space-y-4 p-4"><div className="grid grid-cols-4 gap-2">{tabs.map(({v,l,icon:Icon})=><button key={v} onClick={()=>setType(v)} className={cn('flex min-h-14 flex-col items-center justify-center gap-1 rounded-2xl border border-white/10 bg-white/[.04] text-[10px] font-bold text-slate-400',type===v&&'border-pitch-400/30 bg-pitch-500/10 text-pitch-300')}><Icon size={18}/>{l}</button>)}</div>{q.isLoading?<PageSkeleton/>:q.error?<ErrorState message={(q.error as Error).message} onRetry={()=>q.refetch()}/>:q.data&&<><Card className="border-pitch-400/20 bg-pitch-500/[.07]"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-pitch-500 text-lg font-black text-ink-950">#{faNumber(q.data.current.rank)}</div><div className="min-w-0 flex-1"><p className="text-xs text-pitch-300">جایگاه فعلی شما</p><h3 className="truncate font-extrabold">{q.data.current.firstName} {q.data.current.lastName}</h3></div><strong>{rankingValue(q.data.current,type)}</strong></div></Card><Card className="p-2">{q.data.leaders.map((user,index)=><div key={user._id} className={cn('flex min-h-16 items-center gap-3 rounded-2xl px-3',index<3&&'my-1 bg-white/[.04]')}><span className={cn('grid h-9 w-9 place-items-center rounded-xl text-sm font-black',index===0?'bg-amber-300 text-ink-950':index===1?'bg-slate-300 text-ink-950':index===2?'bg-orange-700 text-white':'bg-white/[.05] text-slate-400')}>{faNumber(index+1)}</span>{user.photoUrl?<img src={user.photoUrl} alt="" className="h-10 w-10 rounded-xl object-cover"/>:<div className="grid h-10 w-10 place-items-center rounded-xl bg-pitch-500/10 font-bold text-pitch-300">{user.firstName[0]}</div>}<div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{user.firstName} {user.lastName}</p><p className="text-[10px] text-slate-500">@{user.username||'footballer'}</p></div><strong className="text-xs text-pitch-300">{rankingValue(user,type)}</strong></div>)}</Card></>}</main></>}
function rankingValue(user:User,type:string){const value=type==='referrals'?user.successfulReferrals:type==='predictors'?user.correctPredictions:type==='all'?user.points:user.weeklyPoints;return `${faNumber(value??0)} ${type==='referrals'?'دعوت':'امتیاز'}`}
