import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, ChevronLeft, ChevronRight, Clock3, XCircle } from 'lucide-react';
import { cn, faNumber } from '@/lib/utils';
import type { Question } from '@/types/api';
import { Card, LoadingButton } from './ui';

export interface SubmitResult { rank: number; feedback: { questionId: string; option: number; correct: boolean; score: number }[]; attempt?: { score?: number; correctCount?: number }; entry?: { score?: number; correctCount?: number }; }
export function QuizRunner({ questions, timerSeconds, submitting, onSubmit }: { questions: Question[]; timerSeconds?: number; submitting: boolean; onSubmit: (answers: {questionId:string;option:number}[], durationMs:number) => Promise<SubmitResult> }) {
  const [index,setIndex]=useState(0); const [answers,setAnswers]=useState<Record<string,number>>({}); const [startedAt]=useState(() => Date.now()); const [remaining,setRemaining]=useState(timerSeconds ?? 0); const [result,setResult]=useState<SubmitResult|null>(null);
  useEffect(()=>{ if(!timerSeconds||result)return; const id=setInterval(()=>setRemaining(v=>{if(v<=1){clearInterval(id);return 0}return v-1}),1000); return()=>clearInterval(id)},[timerSeconds,result]);
  const question=questions[index]; const progress=((index+1)/questions.length)*100; const answered=Object.keys(answers).length; const canSubmit=answered===questions.length;
  const feedbackMap=useMemo(()=>new Map(result?.feedback.map(f=>[f.questionId,f])??[]),[result]);
  if(result){const score=result.attempt?.score??result.entry?.score??result.feedback.reduce((s,f)=>s+f.score,0);const correct=result.attempt?.correctCount??result.entry?.correctCount??result.feedback.filter(f=>f.correct).length;return <div className="space-y-4"><Card className="text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-pitch-500/10 text-2xl font-black text-pitch-300">#{faNumber(result.rank)}</div><h2 className="mt-4 text-xl font-black">نتیجه نهایی</h2><div className="mt-4 grid grid-cols-2 gap-3"><div className="surface-soft p-3"><div className="text-xs text-slate-400">امتیاز</div><strong className="mt-1 block text-xl text-pitch-300">{faNumber(score)}</strong></div><div className="surface-soft p-3"><div className="text-xs text-slate-400">پاسخ صحیح</div><strong className="mt-1 block text-xl">{faNumber(correct)} از {faNumber(questions.length)}</strong></div></div></Card>{questions.map((q,i)=>{const f=feedbackMap.get(q._id);return <Card key={q._id} className={f?.correct?'border-pitch-400/20':'border-rose-400/20'}><div className="flex gap-3">{f?.correct?<CheckCircle2 className="shrink-0 text-pitch-300"/>:<XCircle className="shrink-0 text-rose-300"/>}<div><p className="text-sm font-bold">{faNumber(i+1)}. {q.text}</p><p className="mt-2 text-xs text-slate-400">پاسخ شما: {q.options[f?.option??0]??'بدون پاسخ'}</p>{q.explanation&&<p className="mt-2 text-xs leading-6 text-slate-300">{q.explanation}</p>}</div></div></Card>})}</div>}
  return <Card><div className="flex items-center justify-between text-xs text-slate-400"><span>سؤال {faNumber(index+1)} از {faNumber(questions.length)}</span>{timerSeconds&&<span className={cn('flex items-center gap-1',remaining<20&&'text-rose-300')}><Clock3 size={14}/>{faNumber(remaining)} ثانیه</span>}</div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-pitch-500 transition-all" style={{width:`${progress}%`}}/></div><h2 className="mt-6 text-base font-extrabold leading-8">{question.text}</h2><div className="mt-5 space-y-2">{question.options.map((option,optionIndex)=><button key={option} onClick={()=>setAnswers(a=>({...a,[question._id]:optionIndex}))} className={cn('flex min-h-14 w-full items-center gap-3 rounded-2xl border border-white/10 bg-white/[.035] px-4 text-right text-sm font-semibold transition',answers[question._id]===optionIndex&&'border-pitch-400/40 bg-pitch-500/10 text-pitch-200')}><span className="grid h-7 w-7 shrink-0 place-items-center rounded-xl bg-white/[.06] text-xs">{faNumber(optionIndex+1)}</span>{option}</button>)}</div><div className="mt-6 flex gap-2"><button disabled={index===0} onClick={()=>setIndex(i=>i-1)} className="btn-secondary flex-1"><ChevronRight size={18}/>قبلی</button>{index<questions.length-1?<button onClick={()=>setIndex(i=>i+1)} className="btn-primary flex-1">بعدی<ChevronLeft size={18}/></button>:<LoadingButton disabled={!canSubmit||remaining===0} loading={submitting} onClick={async()=>setResult(await onSubmit(Object.entries(answers).map(([questionId,option])=>({questionId,option})),Date.now()-startedAt))} className="flex-1">ثبت پاسخ‌ها</LoadingButton>}</div><p className="mt-3 text-center text-[10px] text-slate-500">{faNumber(answered)} پاسخ از {faNumber(questions.length)} ثبت شده</p></Card>
}
