import type { PropsWithChildren, ReactNode } from 'react';
import { AlertCircle, ChevronLeft, LoaderCircle, Radio, Trophy } from 'lucide-react';
import { Link } from 'react-router-dom';
import { cn } from '@/lib/utils';

export function Card({ children, className = '' }: PropsWithChildren<{ className?: string }>) { return <section className={cn('surface broadcast-panel p-4', className)}>{children}</section>; }
export function SectionTitle({ title, action, to }: { title: string; action?: string; to?: string }) { return <div className="mb-2 flex items-end justify-between"><div><span className="mb-1 block text-[7px] font-black tracking-[.18em] text-cyan-300" dir="ltr">MATCH CENTER</span><h2 className="text-base font-extrabold tracking-tight">{title}</h2></div>{action && to && <Link to={to} className="inline-flex min-h-9 items-center gap-1 text-[10px] font-bold text-cyan-300">{action}<ChevronLeft size={16}/></Link>}</div>; }
export function Stat({ label, value, icon }: { label: string; value: ReactNode; icon?: ReactNode }) { return <div className="surface-soft min-w-0 p-3"><div className="mb-2 flex items-center gap-2 text-slate-400">{icon}<span className="truncate text-[11px] font-semibold">{label}</span></div><div className="truncate text-lg font-extrabold">{value}</div></div>; }
export function Skeleton({ className = '' }: { className?: string }) { return <div className={cn('broadcast-skeleton animate-pulse rounded-2xl', className)} />; }
export function PageSkeleton() { return <div className="page-skeleton space-y-3 p-4" aria-label="در حال بارگذاری"><div className="broadcast-skeleton-hero relative h-28 overflow-hidden rounded-[1.6rem]"><span className="absolute right-4 top-4 h-3 w-24 rounded-full bg-white/[.07]"/><span className="absolute bottom-5 right-4 h-6 w-44 max-w-[62%] rounded-lg bg-white/[.09]"/></div><div className="grid grid-cols-3 gap-2"><Skeleton className="h-16"/><Skeleton className="h-16"/><Skeleton className="h-16"/></div><Skeleton className="h-44"/><Skeleton className="h-28"/></div>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <Card className="empty-state relative flex min-h-48 flex-col items-center justify-center overflow-hidden text-center"><span className="absolute -left-8 -top-12 h-32 w-32 rounded-full border-[18px] border-cyan-300/[.025]"/><div className="mb-3 grid h-12 w-12 place-items-center rounded-xl bg-cyan-300 text-[#10051d] shadow-[0_10px_26px_rgba(61,226,238,.12)]"><Trophy size={22}/></div><span className="text-[7px] font-black tracking-[.2em] text-fuchsia-300" dir="ltr">WAITING FOR KICK-OFF</span><h3 className="mt-1 font-extrabold">{title}</h3><p className="mt-1 max-w-xs text-[10px] leading-6 text-slate-400">{description}</p>{action && <div className="mt-4">{action}</div>}</Card>; }
export function ErrorState({ message, onRetry }: { message: string; onRetry?: () => void }) { return <Card className="error-state flex min-h-48 flex-col items-center justify-center text-center"><div className="mb-3 grid h-12 w-12 place-items-center rounded-xl bg-rose-400/[.12] text-rose-300"><AlertCircle size={23}/></div><span className="flex items-center gap-1 text-[7px] font-black tracking-[.16em] text-rose-300" dir="ltr"><Radio size={10}/> SIGNAL LOST</span><h3 className="mt-1 font-bold">مشکلی پیش آمد</h3><p className="mt-2 text-[10px] leading-5 text-slate-400">{message}</p>{onRetry && <button onClick={onRetry} className="btn-secondary mt-4">تلاش دوباره</button>}</Card>; }
export function LoadingButton({ loading, children, className = '', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { loading?: boolean }) { return <button {...props} disabled={loading || props.disabled} className={cn('btn-primary', className)}>{loading && <LoaderCircle size={18} className="animate-spin"/>}{children}</button>; }
export function StatusPill({ status }: { status: string }) {
  const labels: Record<string,string> = { scheduled: 'زمان‌بندی‌شده', live: 'زنده', finished: 'تمام‌شده', cancelled: 'لغوشده', active: 'فعال', draft: 'پیش‌نویس' };
  return <span className={cn('chip', status === 'live' || status === 'active' ? 'border-pitch-400/30 bg-pitch-500/10 text-pitch-300' : status === 'cancelled' ? 'border-rose-400/20 bg-rose-500/10 text-rose-300' : '')}>{labels[status] ?? status}</span>;
}
